#!/usr/bin/env bash

set -eu

[[ ${DOCKER_TAG} =~ ([a-z]+)-([a-z]+)-([0-9a-z.]+)$ ]]
ROS_DISTRO=${BASH_REMATCH[2]}

docker build --build-arg ROS_DISTRO=${ROS_DISTRO} \
             -t ${IMAGE_NAME} .
